[workspace]
members = [
    "enumerate",
    "functions",
    "guessing",
    "hello",
    "hey",
    "hi",
    "string",
    "structure"
]



[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3